"""Red box scheme search — parameterise PhreakMe's coin scheme and sweep it.

The important observation is that PhreakMe's whole coin table is generated by a
*single frequency pair*. Reading the server's ``_redbox_segs()`` next to real
Bell ACTS shows what the organisers actually did:

    ACTS                            PhreakMe
    ------------------------------  ------------------------------------------
    1700+2200 played together       split into an ordered alphabet {A, B}
    value = burst COUNT             value = LEVEL (nickel/dime) and ORDER
    nickel 1x66ms, dime 2x66ms      nickel = A@-6dBFS, dime = A@-3dBFS
    quarter 5x33ms                  quarter = A then B
    (no dollar tone)                dollar  = A+B simultaneously
    66/33 ms bursts                 uniform 60 ms segments

Everything except A and B is structure. So when the organisers "change the
frequencies", the structure almost certainly survives and only the pair moves —
which turns an open-ended hunt into a 42-candidate ordered sweep, because the
server's detector can only measure ``MF_ALPHABET`` in the first place
(``_MF_ALL_FREQS`` in whopper/agi/tone_engine.py).

:class:`RedboxScheme` is that parameterisation; :func:`candidates` enumerates the
search space; :func:`fingerprint` and :func:`response_changed` score whether the
far end reacted differently, so a sweep can run unattended over SIP.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

import numpy as np

# Every frequency the PhreakMe detector can measure (_MF_ALL_FREQS). A scheme
# outside this set could not be detected by their own code, so the search space
# is exactly the ordered pairs drawn from here.
MF_ALPHABET: tuple[int, ...] = (700, 900, 1100, 1300, 1500, 1700, 2200)

# The scheme as of last year — the control case for any sweep.
KNOWN_A, KNOWN_B = 1700, 2200

# Last year's non-frequency parameters. A candidate that differs on any of these
# is a different experiment even when the frequency pair is unchanged, so they
# are what ``name`` and ``is_control`` compare against.
CONTROL_DURATION = 0.060
CONTROL_GAP = 0.060
CONTROL_RETURN_GAP = 0.015
CONTROL_NICKEL_DBFS = -6.0
CONTROL_DIME_DBFS = -3.0
CONTROL_LEVEL_DBFS = -3.0

# Ranked candidate list shipped with the package — the analysis that says which
# pairs to spend call minutes on first. ``default_candidates`` prefers it.
RANKED_PATH = Path(__file__).parent / "data" / "redbox-candidates.json"


@dataclass
class RedboxScheme:
    """A complete coin table generated from one frequency pair.

    ``freq_a`` carries nickel, dime, collect and return; ``freq_b`` is the
    quarter's second symbol and the dollar's partner. Levels are *combined*
    dBFS, matching the server's ``Seg.level_dbfs``.
    """

    freq_a: float = KNOWN_A
    freq_b: float = KNOWN_B
    duration: float = CONTROL_DURATION
    gap: float = CONTROL_GAP
    return_gap: float = CONTROL_RETURN_GAP
    nickel_dbfs: float = CONTROL_NICKEL_DBFS
    dime_dbfs: float = CONTROL_DIME_DBFS
    level_dbfs: float = CONTROL_LEVEL_DBFS
    label: str = ""
    rationale: str = ""
    confidence: str = ""

    @property
    def pair(self) -> str:
        return f"{self.freq_a:.0f}->{self.freq_b:.0f}"

    @property
    def name(self) -> str:
        """A label that is unique across every axis the scheme can move on.

        The frequency pair alone is *not* an identity: the search deliberately
        includes candidates that keep 1700->2200 and move the segment length or
        the nickel/dime level split instead. Naming those after the pair made
        three distinct experiments share one name, which let the sweep's resume
        set skip two of them and made the results log ambiguous about which one
        had actually landed.
        """
        if self.label:
            return self.label
        marks = []
        if abs(self.duration - CONTROL_DURATION) > 1e-9:
            marks.append(f"{self.duration * 1000:.0f}ms")
        if abs(self.gap - CONTROL_GAP) > 1e-9:
            marks.append(f"gap{self.gap * 1000:.0f}ms")
        if abs(self.return_gap - CONTROL_RETURN_GAP) > 1e-9:
            marks.append(f"rgap{self.return_gap * 1000:.0f}ms")
        if (abs(self.nickel_dbfs - CONTROL_NICKEL_DBFS) > 1e-9
                or abs(self.dime_dbfs - CONTROL_DIME_DBFS) > 1e-9):
            marks.append(f"n{self.nickel_dbfs:+.0f}/d{self.dime_dbfs:+.0f}")
        if abs(self.level_dbfs - CONTROL_LEVEL_DBFS) > 1e-9:
            marks.append(f"L{self.level_dbfs:+.0f}")
        return self.pair + (" " + " ".join(marks) if marks else "")

    @property
    def is_control(self) -> bool:
        """True only for last year's scheme *exactly*.

        Every parameter counts, not just the pair — a candidate that swaps the
        nickel and dime levels is a prediction about this year, and flagging it
        as "last year's scheme" in the sweep output would be a lie at the one
        moment the operator is deciding what the far end just told them.
        """
        return (
            (self.freq_a, self.freq_b) == (KNOWN_A, KNOWN_B)
            and abs(self.duration - CONTROL_DURATION) < 1e-9
            and abs(self.gap - CONTROL_GAP) < 1e-9
            and abs(self.return_gap - CONTROL_RETURN_GAP) < 1e-9
            and abs(self.nickel_dbfs - CONTROL_NICKEL_DBFS) < 1e-9
            and abs(self.dime_dbfs - CONTROL_DIME_DBFS) < 1e-9
            and abs(self.level_dbfs - CONTROL_LEVEL_DBFS) < 1e-9
        )

    def describe(self) -> str:
        return (f"{self.pair}Hz  {self.duration * 1000:.0f}ms  "
                f"nickel {self.nickel_dbfs:+.0f} / dime {self.dime_dbfs:+.0f} dBFS"
                + (f"  [{self.confidence}]" if self.confidence else "")
                + ("   [control: last year's scheme]" if self.is_control else ""))

    def coin_spec(self) -> dict:
        """Render the full six-symbol table as a ``Config.coin_spec``."""
        a, b = [self.freq_a], [self.freq_b]
        d, g, L = self.duration, self.gap, self.level_dbfs
        return {
            "n": [[a, d, self.nickel_dbfs], [None, g, 0.0]],
            "d": [[a, d, self.dime_dbfs], [None, g, 0.0]],
            "q": [[a, d, L], [None, g, 0.0], [b, d, L], [None, g, 0.0]],
            "$": [[[self.freq_a, self.freq_b], d, L], [None, g, 0.0]],
            "c": [[a, d, L], [None, g, 0.0]] * 3,
            "r": [[a, d, L], [None, self.return_gap, 0.0]] * 6,
        }

    def to_dict(self) -> dict:
        return {"freq_a": self.freq_a, "freq_b": self.freq_b,
                "duration": self.duration, "gap": self.gap,
                "return_gap": self.return_gap,
                "nickel_dbfs": self.nickel_dbfs, "dime_dbfs": self.dime_dbfs,
                "level_dbfs": self.level_dbfs, "label": self.name,
                "confidence": self.confidence, "rationale": self.rationale}

    @classmethod
    def from_dict(cls, d: dict) -> "RedboxScheme":
        known = {f for f in cls.__dataclass_fields__}
        return cls(**{k: v for k, v in (d or {}).items() if k in known})


def _priority(a: int, b: int) -> tuple:
    """Sort key: most-likely first, before any external ranking is applied.

    Heuristic, in order: the control pair; then its reversal; then pairs that
    keep one of the ACTS frequencies (the organisers have shown they like that
    heritage); then pairs drawn from the coin KP/ST variant; then the rest,
    preferring wider separation because close pairs are harder for a Goertzel
    to tell apart.
    """
    acts = {KNOWN_A, KNOWN_B}
    if (a, b) == (KNOWN_A, KNOWN_B):
        tier = 0
    elif (a, b) == (KNOWN_B, KNOWN_A):
        tier = 1
    elif a in acts and b in acts:
        tier = 2
    elif a in acts or b in acts:
        tier = 3
    elif {a, b} & {1500, 2200}:          # _MF_COIN ST pair
        tier = 4
    else:
        tier = 5
    return (tier, -abs(a - b), a, b)


def candidates(
    alphabet: tuple[int, ...] = MF_ALPHABET,
    durations: tuple[float, ...] = (0.060,),
    include_control: bool = True,
) -> list[RedboxScheme]:
    """Every ordered pair from the alphabet, most-likely first."""
    pairs = [(a, b) for a in alphabet for b in alphabet if a != b]
    pairs.sort(key=lambda p: _priority(*p))
    out: list[RedboxScheme] = []
    for d in durations:
        for a, b in pairs:
            s = RedboxScheme(freq_a=a, freq_b=b, duration=d)
            if s.is_control and not include_control:
                continue
            out.append(s)
    # Keep the control first overall so a sweep can establish a baseline.
    out.sort(key=lambda s: (not s.is_control,))
    return out


def _seconds(item: dict, ms_key: str, s_key: str, default: float) -> float:
    """Read a duration given either as ``*_ms`` or as bare seconds."""
    if ms_key in item:
        return float(item[ms_key]) / 1000.0
    return float(item.get(s_key, default))


def load_ranked(path, alphabet: tuple[int, ...] = MF_ALPHABET) -> list[RedboxScheme]:
    """Load an externally ranked candidate list (e.g. from analysis).

    Entries outside ``alphabet`` are dropped: the server's detector cannot
    measure them, so they cannot be the answer.

    Every non-frequency parameter is honoured, because a ranked list earns its
    keep precisely by including the off-frequency hypotheses — a restored 66 ms
    segment, an inverted nickel/dime split — and a loader that read only the
    pair would silently collapse those into duplicates of the control.
    """
    import json

    raw = json.loads(Path(path).read_text())
    items = raw.get("ranked", raw) if isinstance(raw, dict) else raw
    out: list[RedboxScheme] = []
    for it in items:
        a, b = it.get("freq_a"), it.get("freq_b")
        if a is None or b is None:
            continue
        if int(a) not in alphabet or int(b) not in alphabet:
            continue
        out.append(RedboxScheme(
            freq_a=float(a), freq_b=float(b),
            duration=_seconds(it, "duration_ms", "duration", CONTROL_DURATION),
            gap=_seconds(it, "gap_ms", "gap", CONTROL_GAP),
            return_gap=_seconds(it, "return_gap_ms", "return_gap",
                                CONTROL_RETURN_GAP),
            nickel_dbfs=float(it.get("nickel_dbfs", CONTROL_NICKEL_DBFS)),
            dime_dbfs=float(it.get("dime_dbfs", CONTROL_DIME_DBFS)),
            level_dbfs=float(it.get("level_dbfs", CONTROL_LEVEL_DBFS)),
            label=str(it.get("label", "")),
            confidence=str(it.get("confidence", "")),
            rationale=str(it.get("rationale", "")),
        ))
    return _disambiguate(out)


def _disambiguate(schemes: list[RedboxScheme]) -> list[RedboxScheme]:
    """Force every name in a list to be unique.

    ``name`` already separates schemes that differ on any modelled axis, but a
    hand-written file can still supply two identical entries or repeat a
    ``label``. Names are the sweep's resume key and its log key, so a collision
    means a candidate is never dialled and a hit cannot be traced back — cheap
    to prevent here, expensive to notice at the con.
    """
    seen: dict[str, int] = {}
    for i, s in enumerate(schemes, 1):
        n = s.name
        seen[n] = seen.get(n, 0) + 1
        if seen[n] > 1:
            s.label = f"{n} #{i}"
    return schemes


def default_candidates(
    path=None, alphabet: tuple[int, ...] = MF_ALPHABET
) -> list[RedboxScheme]:
    """The list to sweep by default: ranked analysis first, then everything else.

    The shipped ranking covers the pairs with an argument behind them; the rest
    of the ordered pairs are appended in heuristic order so a sweep that
    exhausts the good guesses keeps going rather than stopping at 18 of 42.
    """
    p = Path(path) if path else RANKED_PATH
    ranked: list[RedboxScheme] = []
    if p.exists():
        try:
            ranked = load_ranked(p, alphabet)
        except (OSError, ValueError, TypeError):
            ranked = []
    if not ranked:
        return candidates(alphabet=alphabet)
    covered = {(s.freq_a, s.freq_b) for s in ranked}
    rest = [s for s in candidates(alphabet=alphabet)
            if (s.freq_a, s.freq_b) not in covered]
    return _disambiguate(ranked + rest)


# ---- scoring the far end -----------------------------------------------------


@dataclass
class Fingerprint:
    """A cheap, comparable summary of what the far end sent back."""

    duration: float
    energy: float
    speech_ratio: float
    tone_ratio: float
    band: list[float] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {"duration": round(self.duration, 3),
                "energy": round(self.energy, 6),
                "speech_ratio": round(self.speech_ratio, 4),
                "tone_ratio": round(self.tone_ratio, 4)}


def fingerprint(x: np.ndarray, sr: int = 8000, bands: int = 16) -> Fingerprint:
    """Summarise a far-end recording so two responses can be compared.

    Deliberately coarse. We are not trying to transcribe the prompt, only to
    notice that the challenge said something *different* — which is the signal
    that a coin was accepted.
    """
    if not len(x):
        return Fingerprint(0.0, 0.0, 0.0, 0.0, [0.0] * bands)
    spec = np.abs(np.fft.rfft(x * np.hanning(len(x))))
    freqs = np.fft.rfftfreq(len(x), 1 / sr)
    total = float(np.sum(spec**2)) or 1e-12

    def band_energy(lo, hi):
        return float(np.sum(spec[(freqs >= lo) & (freqs < hi)] ** 2))

    edges = np.linspace(0, sr / 2, bands + 1)
    profile = [band_energy(edges[i], edges[i + 1]) / total for i in range(bands)]
    return Fingerprint(
        duration=len(x) / sr,
        energy=float(np.sqrt(np.mean(x.astype(np.float64) ** 2))),
        speech_ratio=band_energy(300, 900) / total,
        tone_ratio=band_energy(650, 2700) / total,
        band=profile,
    )


def response_changed(baseline: Fingerprint, other: Fingerprint,
                     threshold: float = 0.25) -> tuple[bool, float]:
    """Did the far end respond differently than to the baseline attempt?

    Returns ``(changed, distance)``. Distance is L1 over the normalised band
    profile plus a duration term — enough to catch "a different prompt played"
    without pretending to understand speech.
    """
    # An empty or silent recording carries no comparable spectrum. Without this
    # guard a control call that captured nothing would score every later scheme
    # as "changed", turning the whole sweep into false positives.
    if not baseline.band or not other.band:
        return False, 0.0
    if baseline.duration <= 0 or other.duration <= 0:
        return False, 0.0
    if baseline.energy <= 1e-6 or other.energy <= 1e-6:
        return False, 0.0
    spectral = float(np.sum(np.abs(np.array(baseline.band) - np.array(other.band))))
    longest = max(baseline.duration, other.duration) or 1.0
    temporal = abs(baseline.duration - other.duration) / longest
    dist = spectral + temporal
    return dist >= threshold, dist
